import { constants } from "node:fs";
import { open, writeFile } from "node:fs/promises";
import path from "node:path";
import { detectProject } from "./detect-project.js";
import type {
  DetectedProject,
  InitOptions,
  InitPlan,
  InitPlannedFile,
  InitResult,
  InitValidation,
} from "./types.js";

const configFile = "vii.config.ts";
const phases = ["analyze", "plan", "preview", "apply", "validate", "report"] as const;

export async function initProject(
  inputRoot: string,
  options: InitOptions = {},
): Promise<InitResult> {
  const detection = await detectProject(inputRoot);
  const root = detection.root;
  const target = path.resolve(root, configFile);
  const expectedContent = createConfig(detection);
  const inspection = await inspectTarget(target, expectedContent);
  const conflicts = createConflicts(detection, inspection);
  const files =
    inspection === "missing" && conflicts.length === 0 ? [createPlannedFile(expectedContent)] : [];
  const plan: InitPlan = { conflicts, files };
  const blocked = conflicts.length > 0;
  let applied = false;

  if (!blocked && !options.dryRun && files.length > 0) {
    await writeFile(target, expectedContent, { encoding: "utf8", flag: "wx" });
    applied = true;
  }

  const validation = await validateTarget(target, expectedContent, plan, options.dryRun === true);
  const status = blocked
    ? "blocked"
    : options.dryRun
      ? "dry-run"
      : applied
        ? "applied"
        : "unchanged";

  return {
    applied,
    detection,
    phases,
    plan,
    report: {
      status,
      files: files.map((file) => file.path),
      message: createMessage(status, files),
    },
    validation,
  };
}

function createConfig(project: DetectedProject): string {
  return [
    "/** Vii project configuration generated by `vii init`. */",
    "export default " + JSON.stringify({ framework: project.framework }, null, 2) + " as const;",
    "",
  ].join("\n");
}

function createPlannedFile(content: string): InitPlannedFile {
  return { action: "create", content, path: configFile };
}

async function inspectTarget(
  target: string,
  expectedContent: string,
): Promise<"missing" | "same" | "different" | "symlink"> {
  let handle;
  try {
    handle = await open(target, constants.O_RDONLY | constants.O_NOFOLLOW);
    return (await handle.readFile("utf8")) === expectedContent ? "same" : "different";
  } catch (error) {
    if (isMissingFile(error)) {
      return "missing";
    }
    if (isSymlink(error)) {
      return "symlink";
    }
    return "different";
  } finally {
    await handle?.close();
  }
}

function createConflicts(
  detection: DetectedProject,
  inspection: "missing" | "same" | "different" | "symlink",
): readonly string[] {
  const conflicts = detection.conflicts.map((conflict) => conflict.message);
  if (detection.framework === "unknown" || detection.framework === "mixed") {
    conflicts.push("framework detection is ambiguous; select one explicitly");
  }
  if (inspection === "different") {
    conflicts.push(`${configFile} already exists with local changes`);
  }
  if (inspection === "symlink") {
    conflicts.push(`${configFile} is a symbolic link and cannot be changed safely`);
  }
  return conflicts;
}

async function validateTarget(
  target: string,
  expectedContent: string,
  plan: InitPlan,
  dryRun: boolean,
): Promise<InitValidation> {
  if (plan.conflicts.length > 0) {
    return { errors: plan.conflicts, files: [], passed: false };
  }
  if (dryRun && plan.files.length > 0) {
    return { errors: [], files: plan.files.map((file) => file.path), passed: true };
  }
  const inspection = await inspectTarget(target, expectedContent);
  return inspection === "same"
    ? { errors: [], files: [], passed: true }
    : { errors: [`${configFile} failed validation`], files: [], passed: false };
}

function createMessage(
  status: InitResult["report"]["status"],
  files: readonly InitPlannedFile[],
): string {
  if (status === "blocked") {
    return "vii init did not change the project";
  }
  if (status === "unchanged") {
    return "vii init found no changes to apply";
  }
  return status === "dry-run"
    ? `vii init would create ${files.length} file`
    : `vii init created ${files.length} file`;
}

function isMissingFile(error: unknown): boolean {
  return typeof error === "object" && error !== null && "code" in error && error.code === "ENOENT";
}

function isSymlink(error: unknown): boolean {
  return typeof error === "object" && error !== null && "code" in error && error.code === "ELOOP";
}
