import type {
  DTCGColorValue,
  DTCGDimensionValue,
  DTCGDurationValue,
  DTCGTokenValue,
  ResolvedToken,
  TokenGraph,
} from "./dtcg-types.js";

export interface GeneratorOptions {
  prefix?: string;
  selector?: string;
  preserveAliases?: boolean;
}

export function formatTokenValueToCss(value: DTCGTokenValue): string {
  if (typeof value === "string" || typeof value === "number") {
    return String(value);
  }
  if (Array.isArray(value)) {
    if (value.length === 4) {
      return `cubic-bezier(${value[0]}, ${value[1]}, ${value[2]}, ${value[3]})`;
    }
    return value.join(", ");
  }
  if ("colorSpace" in value) {
    const color = value as DTCGColorValue;
    const [c1, c2, c3] = color.components;
    const alpha = color.alpha !== undefined && color.alpha < 1 ? ` / ${color.alpha}` : "";
    if (color.colorSpace === "srgb") {
      const r = Math.round(c1 * 255);
      const g = Math.round(c2 * 255);
      const b = Math.round(c3 * 255);
      return alpha ? `rgb(${r} ${g} ${b}${alpha})` : `rgb(${r} ${g} ${b})`;
    }
    return `color(${color.colorSpace} ${c1} ${c2} ${c3}${alpha})`;
  }
  if ("unit" in value) {
    const val = value as DTCGDimensionValue | DTCGDurationValue;
    return `${val.value}${val.unit}`;
  }
  return JSON.stringify(value);
}

export function generateCss(graph: TokenGraph, options: GeneratorOptions = {}): string {
  const selector = options.selector ?? ":root";
  const preserveAliases = options.preserveAliases ?? false;

  const sortedTokens = Array.from(graph.tokens.values()).sort((a, b) =>
    a.cssVariable.localeCompare(b.cssVariable),
  );

  const lines: string[] = [`${selector} {`];

  for (const token of sortedTokens) {
    let cssValue: string;
    if (preserveAliases && token.isAlias && token.originalAlias) {
      const targetTokenName = token.originalAlias.slice(1, -1);
      const target = graph.tokens.get(targetTokenName);
      cssValue = target ? `var(${target.cssVariable})` : formatTokenValueToCss(token.value);
    } else {
      cssValue = formatTokenValueToCss(token.value);
    }
    lines.push(`  ${token.cssVariable}: ${cssValue};`);
  }

  lines.push("}");
  return lines.join("\n");
}

export function generateTypeScript(graph: TokenGraph): string {
  const sortedTokens = Array.from(graph.tokens.values()).sort((a, b) =>
    a.name.localeCompare(b.name),
  );

  const entries = sortedTokens.map((t) => {
    const serializedVal = JSON.stringify(t.value);
    return `  "${t.name}": ${serializedVal},`;
  });

  const cssVars = sortedTokens.map((t) => `  "${t.name}": "${t.cssVariable}",`);

  return `// Generated by Vii Token Prototype - Deterministic build artifact
export const TOKENS = {
${entries.join("\n")}
} as const;

export const CSS_VARIABLES = {
${cssVars.join("\n")}
} as const;

export type TokenName = keyof typeof TOKENS;
export type CssVariableName = typeof CSS_VARIABLES[TokenName];
`;
}

export interface TokenManifestItem {
  name: string;
  type: string;
  value: DTCGTokenValue;
  cssVariable: string;
  isAlias: boolean;
  originalAlias?: string | undefined;
}

export function generateJsonManifest(graph: TokenGraph): string {
  const sortedTokens = Array.from(graph.tokens.values()).sort((a, b) =>
    a.name.localeCompare(b.name),
  );

  const manifest: Record<string, TokenManifestItem> = {};
  for (const t of sortedTokens) {
    manifest[t.name] = {
      name: t.name,
      type: t.type,
      value: t.value,
      cssVariable: t.cssVariable,
      isAlias: t.isAlias,
      originalAlias: t.originalAlias,
    };
  }

  return JSON.stringify(manifest, null, 2);
}
